// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdDtCtARpJp-UdsmCSpj4vcF1GA6yT1W4',
    appId: '1:211366807960:web:2b74c11d417a3f01ff03ed',
    messagingSenderId: '211366807960',
    projectId: 'nano-banana22222',
    authDomain: 'nano-banana22222.firebaseapp.com',
    storageBucket: 'nano-banana22222.firebasestorage.app',
    databaseURL: 'https://nano-banana22222-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-D8250KVESK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtzo3GV3h59M6ZGGXZ9HpK2052be1Fi_8',
    appId: '1:211366807960:android:838fd5a91308438cff03ed',
    messagingSenderId: '211366807960',
    projectId: 'nano-banana22222',
    storageBucket: 'nano-banana22222.firebasestorage.app',
    databaseURL: 'https://nano-banana22222-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzo3GV3h59M6ZGGXZ9HpK2052be1Fi_8',
    appId: '1:211366807960:ios:91446d227db50a49ff03ed',
    messagingSenderId: '211366807960',
    projectId: 'nano-banana22222',
    storageBucket: 'nano-banana22222.firebasestorage.app',
    iosBundleId: 'com.jessica.nanobanana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtzo3GV3h59M6ZGGXZ9HpK2052be1Fi_8',
    appId: '1:211366807960:ios:91446d227db50a49ff03ed',
    messagingSenderId: '211366807960',
    projectId: 'nano-banana22222',
    storageBucket: 'nano-banana22222.firebasestorage.app',
    iosBundleId: 'com.jessica.nanobanana',
  );
}


